/* ===== wshop.js : 상점 = "태엽 공방" (진열 선반 · 입어보는 무대 · 부엉이 주인장) ===== */
const WS={sel:{ch:null,wp:null,pt:null},sayT:0,sayFull:'',fx:[],jump:0,swing:0,coinShow:null,bg:null,lastTab:null,newT:0,poorT:0,hover:-1};
const WS_LIST=k=>k==='ch'?CHARS:k==='wp'?WEAPONS:PETS;
const WS_OWL=["..oo....oo..",".oBBo..oBBo.",".oBBBooBBBo.","oBEEEBBEEEBo","oBEPEBBEPEBo","oBEEEBBEEEBo","oBBBBKKBBBBo",".obBBKKBBbo.",".obBGGGGBbo.",".obBGbbGBbo.","..obBBBBbo..","...oKo.oKo.."];
const WS_OWLP={o:'#1a1208',B:'#c89a40',b:'#8a6420',E:'#fff4d0',P:'#1a1a1a',K:'#ff9a3a',G:'#6a5a3a'};
const WS_W=320,WS_H=170;
function wsTier(it){const p=it.price||0;return p===0?{n:'기본',c:'#a8b8c0',k:0}:p<700?{n:'일반',c:'#8ff0b0',k:1}:p<2000?{n:'희귀',c:'#6ab8ff',k:2}:p<4000?{n:'영웅',c:'#c88aff',k:3}:{n:'전설',c:'#ffd166',k:4}}
function wsSelOf(k){const inv=shopInv();if(WS.sel[k]==null)WS.sel[k]=inv.eq[k]||0;return WS.sel[k]}
function wsSay(t){if(t===WS.sayFull)return;WS.sayFull=t;WS.sayT=performance.now()}
function wsLineFor(k,i){const inv=shopInv(),it=WS_LIST(k)[i],own=inv.inv[k].includes(i),eq=inv.eq[k]===i,T=wsTier(it);
 if(eq)return ['지금 딱 그걸 쓰고 있네!','그거 참 잘 어울린다니까.','역시 그게 최고지!'][i%3];
 if(own)return '이미 네 거야. '+it.name+', 다시 장착해볼래?';
 if(inv.coins<it.price)return (T.k>=4?'그건 우리 가게 보물이야! ':'')+it.name+'? 코인이 '+(it.price-inv.coins)+'개 모자라.';
 if(T.k>=4)return '오오, '+it.name+'! 공방에서 제일 귀한 물건이지.';
 return k==='ch'?it.name+'의 옷이야. 한번 입어봐!':k==='wp'?it.name+'… 날이 아주 잘 섰지. 휘둘러봐!':it.name+'는 순한 아이야. '+it.desc+'!'}
function wsBuild(){const m=$('shopModal');if(!m||$('wsMain'))return;m.classList.add('wsFull');
 const main=document.createElement('div');main.id='wsMain';
 main.innerHTML='<div id="wsLeft"><div id="wsStageBox"><canvas id="wsCv" width="'+WS_W+'" height="'+WS_H+'"></canvas><div id="wsBubble"><span></span></div><div id="wsTry"></div></div><div id="wsInfo"></div></div><div id="wsRight"></div>';
 const tabs=m.querySelector('.shopTabs'),body=m.querySelector('.rushBody');m.insertBefore(main,body);main.querySelector('#wsRight').appendChild(tabs);main.querySelector('#wsRight').appendChild(body);
 const bar=m.querySelector('.rushBar span');if(bar&&!$('wsTitle'))bar.insertAdjacentHTML('afterbegin','<b id="wsTitle">⚙ 태엽 공방</b> ');
 const pick=i=>{if(WS.sel[shopTab]===i)return;WS.sel[shopTab]=i;try{sfx(700,.05,'triangle',.03,900)}catch(_){}if(shopTab==='wp')WS.swing=performance.now();wsRefresh()};
 $('shopGrid').addEventListener('click',e=>{const d=e.target.closest('.wsItem');if(!d)return;const i=+d.dataset.i;if(WS.sel[shopTab]===i&&e.detail>=2){wsAct();return}pick(i)});
 /* v122: 마우스를 올리기만 해서는 고르지 않음 — 눌러야 고름 */
 addEventListener('keydown',e=>{const mm=$('shopModal');if(!mm||mm.hidden)return;const k=e.code,L=WS_LIST(shopTab).length,s=wsSelOf(shopTab);let n=null;
  if(k==='ArrowRight'||k==='KeyD')n=(s+1)%L;else if(k==='ArrowLeft'||k==='KeyA')n=(s+L-1)%L;else if(k==='ArrowDown'||k==='KeyS')n=Math.min(L-1,s+wsCols());else if(k==='ArrowUp'||k==='KeyW')n=Math.max(0,s-wsCols());
  else if(k==='Enter'||k==='Space'){wsAct();e.preventDefault();e.stopPropagation();return}else if(k==='Escape'){closeShop();e.preventDefault();e.stopPropagation();return}
  else if(/^Digit[123]$/.test(k)||k==='KeyQ'||k==='KeyE'||k==='Tab'){const T=['ch','wp','pt'];shopTab=k.startsWith('Digit')?T[+k.slice(5)-1]:T[(T.indexOf(shopTab)+(k==='KeyQ'?2:1))%3];renderShop();e.preventDefault();return}
  if(n!=null){pick(n);const el=document.querySelector('#shopGrid .wsItem.sel');if(el&&el.scrollIntoView)el.scrollIntoView({block:'nearest'});e.preventDefault();e.stopPropagation()}},true)}
function wsCols(){const g=$('shopGrid');if(!g)return 4;const it=g.querySelector('.wsItem');if(!it)return 4;return Math.max(1,Math.round(g.clientWidth/it.getBoundingClientRect().width))}
function wsItemHTML(k,i){const inv=shopInv(),it=WS_LIST(k)[i],own=inv.inv[k].includes(i),eq=inv.eq[k]===i,sel=wsSelOf(k)===i,poor=!own&&inv.coins<it.price,T=wsTier(it);
 const tag=eq?'<em class="tg eq">장착 중</em>':own?'<em class="tg own">✓ 보유</em>':'<em class="tg'+(poor?' poor':'')+'">🪙 '+it.price+'</em>';
 return '<div class="wsItem t'+T.k+(sel?' sel':'')+(eq?' eq':'')+(own?' own':'')+'" data-i="'+i+'" style="--tc:'+T.c+';--sw:'+((i*37)%7-3)+'deg;--dl:'+(i*.13).toFixed(2)+'s;--ad:'+(i*35)+'ms"><div class="dome"><canvas width="96" height="96" data-k="'+k+'" data-i="'+i+'"></canvas></div>'+tag+'<b><i>'+'★'.repeat(Math.max(0,T.k))+'</i>'+it.name+'</b></div>'}
function wsStatRows(k,i){const inv=shopInv(),e=inv.eq[k],L=WS_LIST(k),row=(lab,v,v0,max,fmt,ico,fmtD)=>{const d=v-v0,pc=Math.max(4,Math.min(100,v/max*100)),pc0=Math.max(0,Math.min(100,v0/max*100));
  return '<div class="wsRow"><span>'+ico+' '+lab+'</span><div class="wsBar"><i class="base" style="width:'+pc0+'%"></i><i class="'+(d>0?'up':d<0?'dn':'')+'" style="width:'+pc+'%"></i><u style="left:'+pc0+'%"></u></div><b>'+fmt(v)+(Math.abs(d)>1e-6?' <small class="'+(d>0?'up':'dn')+'">'+(d>0?'▲':'▼')+(fmtD||fmt)(Math.abs(d))+'</small>':'')+'</b></div>'};
 if(k==='ch'){const s=charStats(i),s0=charStats(e),mh=Math.max(...CHARS.map((_,j)=>charStats(j).hp)),md=Math.max(...CHARS.map(c=>c.dash));return row('체력',s.hp,s0.hp,mh,v=>Math.round(v),'❤')+row('대시',s.dash,s0.dash,md,v=>v+'칸','⚡')}
 if(k==='wp'){const w=L[i],w0=L[e],mx=f=>Math.max(...L.map(x=>x[f]||0))||1;let h=row('피해',w.dmg,w0.dmg,mx('dmg'),v=>'×'+v.toFixed(2),'⚔',v=>v.toFixed(2))+row('치명',w.crit||0,w0.crit||0,Math.max(.01,mx('crit')),v=>Math.round(v*100)+'%','✦')+row('그로기',w.grogi||0,w0.grogi||0,Math.max(.01,mx('grogi')),v=>'+'+Math.round(v*100)+'%','◎');
  const rg=w.range||0,rg0=w0.range||0;h+=row('사거리',rg+10,rg0+10,Math.max(...L.map(x=>(x.range||0)+10)),v=>(v-10>0?'+':'')+(v-10),'↔',v=>String(Math.round(v)));if(w.sp)h+='<div class="wsSp">✦ 필살기 · '+w.sp+'</div>';return h}
 return '<div class="wsPet">✦ '+L[i].desc+'</div>'+(e!==i?'<div class="wsPet old">지금 함께하는 친구: '+L[e].name+' · '+L[e].desc+'</div>':'')}
function wsRefresh(){const k=shopTab,i=wsSelOf(k),inv=shopInv(),it=WS_LIST(k)[i],own=inv.inv[k].includes(i),eq=inv.eq[k]===i,poor=!own&&inv.coins<it.price,T=wsTier(it);
 document.querySelectorAll('#shopGrid .wsItem').forEach(d=>d.classList.toggle('sel',+d.dataset.i===i));
 const inf=$('wsInfo');if(inf){inf.style.setProperty('--tc',T.c);inf.innerHTML='<div class="wsHead"><b>'+it.name+'</b><span class="tier">'+'★'.repeat(Math.max(1,T.k))+' '+T.n+'</span>'+(eq?'<span class="chip eq">장착 중</span>':own?'<span class="chip own">보유</span>':'')+'</div><div class="wsSub">'+(it.sub||(k==='wp'?'무기':k==='pt'?'펫':''))+' · '+(k==='pt'?'함께 다니며 도와주는 친구':it.desc)+'</div>'+wsStatRows(k,i)+
  '<button id="wsBtn" class="'+(eq?'eq':own?'own':poor?'poor':'buy')+'"'+(eq?' disabled':'')+'>'+(eq?'✓ 장착 중':own?'장착하기':'🪙 '+it.price+' · 구매하고 장착')+(!own&&!poor?'<small>구매 후 남는 코인 '+(inv.coins-it.price)+'</small>':(!own&&poor?'<small>'+(it.price-inv.coins)+'코인 더 필요해요</small>':''))+'</button>'}
 const b=$('wsBtn');if(b)b.onclick=wsAct;const tr=$('wsTry');if(tr){tr.textContent=eq?'':own?'👗 갈아입어 보는 중':'🔍 입어보는 중 · 아직 내 것이 아니에요';tr.style.display=eq?'none':''}wsSay(wsLineFor(k,i))}
function wsAct(){const k=shopTab,i=wsSelOf(k),inv=shopInv(),it=WS_LIST(k)[i],own=inv.inv[k].includes(i);initAudio();
 if(inv.eq[k]===i)return;
 if(!own){if(inv.coins<it.price){const b=$('wsBtn');if(b){b.classList.remove('shake');void b.offsetWidth;b.classList.add('shake')}const ct=document.querySelector('#shopModal .coinTag');if(ct){ct.classList.remove('poorShake');void ct.offsetWidth;ct.classList.add('poorShake')}WS.poorT=performance.now();try{sfx(140,.15,'square',.04,90)}catch(e){}wsSay('앗, 코인이 '+(it.price-inv.coins)+'개 모자라! 보스를 더 이겨보자.');return}
  inv.coins-=it.price;inv.inv[k].push(i);inv.eq[k]=i;const T=wsTier(it);try{sfx(660,.2,'triangle',.05,1200);sfx(990,.25,'triangle',.04,1500);perc('chime',audio.currentTime+.1,.8);if(T.k>=3){perc('crash',audio.currentTime+.05,.5);voice('bell',84,.6,.04,audio.currentTime+.25);voice('bell',91,.8,.04,audio.currentTime+.4)}}catch(e){}
  WS.fx.push({t:performance.now(),kind:'buy',c:T.c,big:T.k>=3});WS.jump=performance.now();WS.newT=performance.now();saveNow();renderShop();wsSay(T.k>=4?'전설의 '+it.name+'! 이건 정말 대단한 거야!':['고마워! 정말 잘 어울려!','좋은 거래였어! 잘 써줘.','와, 딱 네 거네!'][i%3]);wsStamp();return}
 inv.eq[k]=i;try{sfx(520,.1,'triangle',.04,800);sfx(780,.12,'triangle',.03,1000)}catch(e){}WS.fx.push({t:performance.now(),kind:'eq',c:wsTier(it).c});WS.jump=performance.now();saveNow();renderShop();wsSay('좋아, 준비 완료!')}
function wsStamp(){const it=document.querySelector('#shopGrid .wsItem.sel');if(!it)return;const s=document.createElement('div');s.className='wsStamp';s.textContent='SOLD';it.appendChild(s);setTimeout(()=>s.remove(),1400)}
function wsCoins(){const el=$('shopCoins');if(!el)return;const v=shopInv().coins;if(WS.coinShow==null)WS.coinShow=v;if(Math.abs(WS.coinShow-v)<.5)WS.coinShow=v;else WS.coinShow+=(v-WS.coinShow)*.12;const t=String(Math.round(WS.coinShow));if(el.textContent!==t)el.textContent=t}
/* ---- 무대 배경 (고정 부분) ---- */
function wsBg(){if(WS.bg)return WS.bg;const cv=document.createElement('canvas');cv.width=WS_W;cv.height=WS_H;const c=cv.getContext('2d'),r=rng(hash('wsbg2')),F=(x,y,w,h,col)=>{c.fillStyle=col;c.fillRect(x,y,w,h)};c.imageSmoothingEnabled=false;
 const g=c.createLinearGradient(0,0,0,WS_H);g.addColorStop(0,'#2e1c10');g.addColorStop(1,'#160e08');F(0,0,WS_W,WS_H,g);
 for(let y=10;y<118;y+=8)for(let x=((y/8)%2)*8-8;x<WS_W;x+=16){F(x,y,15,7,r()<.5?'#36220f':'#2f1d0d');if(r()<.08)F(x+2,y+1,4,2,'#3e2814');F(x,y+7,16,1,'#1a0f07')}
 /* 천장 파이프 */F(0,0,WS_W,10,'#1a0f07');F(0,4,WS_W,4,'#6a5a3a');F(0,4,WS_W,1,'#a8905a');for(let x=18;x<WS_W;x+=46){F(x,2,6,8,'#8a7448');F(x+1,2,1,8,'#c8b078')}F(290,8,6,26,'#6a5a3a');F(290,8,1,26,'#a8905a');F(286,32,14,5,'#8a7448');
 /* 왼쪽 공구판 */F(10,20,70,50,'#3a2a16');F(10,20,70,2,'#5a4020');for(let yy=26;yy<68;yy+=6)for(let xx=14;xx<78;xx+=6)F(xx,yy,1,1,'#1a1008');
 F(18,28,3,26,'#8a8a90');F(15,26,9,5,'#8a8a90');F(17,27,5,3,'#3a2a16');/*렌치*/F(32,28,12,6,'#6a6a70');F(37,34,3,20,'#8a5a2a');/*망치*/F(52,26,2,28,'#c8a860');F(50,52,6,3,'#c8a860');/*드라이버*/
 for(let k=0;k<3;k++){c.fillStyle='#8a7448';c.beginPath();c.arc(66,34+k*12,4,0,TAU);c.fill();F(65,33+k*12,2,2,'#3a2a16')}
 /* 오른쪽 선반 */for(const sy of [42,74]){F(214,sy,70,4,'#6a4424');F(214,sy+4,70,2,'#2a1a0e');for(let k=0;k<6;k++){const x=218+k*11,h=5+Math.floor(r()*9),col=['#8a7a50','#5a8a8a','#a86a3a','#c8a860','#6a6a8a','#8a4a4a'][Math.floor(r()*6)];if(r()<.4){c.fillStyle=col;c.beginPath();c.arc(x+3,sy-4,4,0,TAU);c.fill();F(x+2,sy-5,2,2,'#1a1208')}else{F(x,sy-h,7,h,col);F(x+5,sy-h,2,h,'#00000055');F(x+1,sy-h,1,h,'#ffffff22')}}}
 /* 바닥 */F(0,118,WS_W,52,'#1e140c');for(let x=0;x<WS_W;x+=22){F(x,118,21,52,'#24180e');F(x+21,118,1,52,'#140c06');F(x+4,130+(x%3)*8,6,1,'#2c1e12')}F(0,118,WS_W,2,'#3a2616');
 /* 작업대 (왼쪽 앞) */F(8,112,62,6,'#6a4424');F(8,112,62,1,'#8a6434');F(12,118,4,22,'#4a2e16');F(62,118,4,22,'#4a2e16');F(22,104,14,8,'#5a6a7a');F(24,106,10,4,'#8ae8ff');F(42,106,10,6,'#c89a40');
 return WS.bg=cv}
function wsOwl(c,x,y,now,s){const typing=WS.sayFull&&(now-WS.sayT)/28<WS.sayFull.length,blink=(now%3800)<140,tilt=Math.round(Math.sin(now/900)),flap=(now-WS.jump)<700?Math.round(Math.sin((now-WS.jump)/60)*2):0,beak=typing&&Math.floor(now/90)%2;
 for(let j=0;j<WS_OWL.length;j++)for(let i=0;i<12;i++){let ch=WS_OWL[j][i];if(ch==='.')continue;if(blink&&(ch==='E'||ch==='P'))ch='b';c.fillStyle=WS_OWLP[ch];c.fillRect(x+(i-6)*s+(j<7?tilt:0),y+(j-12)*s,s,s)}
 if(beak){c.fillStyle='#2a1208';c.fillRect(x-s+tilt,y-4*s,2*s,s)}
 /* 날개 */c.fillStyle='#8a6420';c.fillRect(x-7*s,y-6*s-flap,s,4*s);c.fillRect(x+6*s,y-6*s-flap,s,4*s);
 /* 외알 안경 + 줄 */c.strokeStyle='#ffe36b';c.lineWidth=1;c.beginPath();c.arc(x+2.5*s+tilt,y-7.5*s,s*1.8,0,TAU);c.stroke();c.fillStyle='#ffe36b';c.fillRect(x+4*s+tilt,y-6*s,1,5*s)}
function wsText(c,t,x,y,col,sz){c.font='900 '+sz+'px '+FONT_STACK;c.textAlign='center';c.fillStyle='#000';c.fillText(t,x+1,y+1);c.fillStyle=col;c.fillText(t,x,y);c.textAlign='left'}
function wsWeaponCopy(c,w,hx,hy,ang,sc,now,dx,dy,ww,hh){ctx.save();ctx.clearRect(0,0,ww,hh);drawWeaponShape(w,hx,hy,ang,0,sc,now,1);ctx.restore();c.drawImage($('game'),0,0,ww*SS,hh*SS,dx,dy,ww,hh)}
function wsStage(now){const cv=$('wsCv');if(!cv)return;const c=cv.getContext('2d'),t=now/1000,inv=shopInv(),k=shopTab,sel=wsSelOf(k),it=WS_LIST(k)[sel],T=wsTier(it),col=T.c;c.imageSmoothingEnabled=false;c.globalAlpha=1;c.drawImage(wsBg(),0,0);
 /* 벽시계 톱니 (돌아감) */{const gx=150,gy=36;c.save();c.translate(gx,gy);c.rotate(t*.25);c.fillStyle='#4a3620';for(let n=0;n<12;n++){c.rotate(TAU/12);c.fillRect(-3,-25,6,7)}c.beginPath();c.arc(0,0,20,0,TAU);c.fill();c.fillStyle='#2a1a0e';for(let n=0;n<5;n++){c.beginPath();c.arc(Math.cos(n*TAU/5)*11,Math.sin(n*TAU/5)*11,3.5,0,TAU);c.fill()}c.beginPath();c.arc(0,0,5,0,TAU);c.fill();c.restore();
  c.save();c.translate(gx+28,gy+18);c.rotate(-t*.5);c.fillStyle='#3a2a18';for(let n=0;n<8;n++){c.rotate(TAU/8);c.fillRect(-2,-13,4,5)}c.beginPath();c.arc(0,0,10,0,TAU);c.fill();c.fillStyle='#1a0f07';c.beginPath();c.arc(0,0,3,0,TAU);c.fill();c.restore()}
 /* 증기 */for(let n=0;n<5;n++){const q=((t*.35)+n/5)%1;c.globalAlpha=(1-q)*.22;c.fillStyle='#e8e0d0';const r=3+q*9;c.beginPath();c.arc(293+Math.sin(q*6+n)*4,36+q*30,r,0,TAU);c.fill()}c.globalAlpha=1;
 /* 흔들리는 전등 + 빛 + 먼지 */const px=128,py=136,la=Math.sin(t*1.1)*.12,lx=px+Math.sin(la)*34,ly=10+Math.cos(la)*34;c.strokeStyle='#1a1208';c.lineWidth=1;c.beginPath();c.moveTo(px,8);c.lineTo(lx,ly);c.stroke();
 c.globalAlpha=.11;c.fillStyle='#ffd98a';c.beginPath();c.moveTo(lx-5,ly+4);c.lineTo(lx+5,ly+4);c.lineTo(lx+56,py+10);c.lineTo(lx-56,py+10);c.closePath();c.fill();
 for(let n=0;n<14;n++){const q=((t*.05)+n/14)%1,yy=ly+8+q*(py-ly),sp=4+(yy-ly)*.8,xx=lx+Math.sin(n*2.3+t*.7)*sp*.7;c.globalAlpha=.5*Math.sin(q*Math.PI);c.fillStyle='#fff0c0';c.fillRect(Math.round(xx),Math.round(yy),1,1)}
 c.globalAlpha=1;c.fillStyle='#c89a40';c.fillRect(Math.round(lx)-6,Math.round(ly),12,5);c.fillStyle='#8a6420';c.fillRect(Math.round(lx)-6,Math.round(ly)+4,12,1);c.fillStyle='#fff4c0';c.fillRect(Math.round(lx)-2,Math.round(ly)+5,4,2);
 /* 회전 무대 */c.fillStyle='#0c0806';c.beginPath();c.ellipse(px,py+6,56,13,0,0,TAU);c.fill();c.fillStyle='#5a3a1a';c.beginPath();c.ellipse(px,py+3,54,12,0,0,TAU);c.fill();c.fillStyle='#a8803a';c.beginPath();c.ellipse(px,py,54,12,0,0,TAU);c.fill();c.fillStyle='#c8a050';c.beginPath();c.ellipse(px,py-1,48,10,0,0,TAU);c.fill();
 for(let n=0;n<20;n++){const a=n*TAU/20+t*.9,sx=px+Math.cos(a)*50,sy=py+Math.sin(a)*11;if(Math.sin(a)<0)continue;c.fillStyle=n%2?'#ffe9a8':'#6a4a22';c.fillRect(Math.round(sx)-1,Math.round(sy),2,2)}
 c.globalAlpha=.3+.12*Math.sin(t*3);c.fillStyle=col;c.beginPath();c.ellipse(px,py-1,42,8,0,0,TAU);c.fill();c.globalAlpha=1;
 /* 등급 빛기둥 */if(T.k>=2){for(let n=0;n<(T.k>=4?18:T.k>=3?12:7);n++){const q=((t*.4)+n/12)%1,xx=px+Math.sin(n*2.1)*36*(1-q*.3),yy=py-q*90;c.globalAlpha=(1-q)*.8;c.fillStyle=n%3?col:'#ffffff';c.fillRect(Math.round(xx),Math.round(yy),n%4?1:2,n%4?2:3)}c.globalAlpha=1}
 if(T.k>=4){c.globalAlpha=.12+.06*Math.sin(t*2);c.fillStyle=col;c.fillRect(px-40,py-100,80,100);c.globalAlpha=1}
 /* 주인공 (입어보기) */const save={ch:inv.eq.ch,wp:inv.eq.wp,pt:inv.eq.pt};inv.eq[k]=sel;const jt=(now-WS.jump)/1000,jy=jt<.5?-Math.round(Math.sin(jt/.5*Math.PI)*16):0,s=3,fl=k==='ch'&&Math.floor(t/2.2)%2===1,hx=Math.round(px-5.5*s),hy=Math.round(py-3-11.5*s+jy);
 c.globalAlpha=.45;c.fillStyle='#000';c.beginPath();c.ellipse(px,py,16-Math.abs(jy)*.4,4,0,0,TAU);c.fill();c.globalAlpha=1;
 try{drawKnight(c,hx,hy,s,fl,null,now/430)}catch(e){}
 try{const w=WEAPONS[inv.eq.wp]||WEAPONS[0],st=(now-WS.swing)/1000,auto=(t%3)/3,sw=st<.45?st/.45:(k==='wp'&&auto>.74?(auto-.74)/.26:-1),dir=fl?-1:1,bx=px+11*dir,by=py-27+jy;let ang;
  if(sw>=0&&sw<=1){const e=1-Math.pow(1-sw,3);ang=-2.3+e*3.0;c.globalAlpha=.4*(1-sw);c.strokeStyle=w.trail||w.col||'#fff';c.lineWidth=4;c.beginPath();c.arc(bx,by,26,-2.3,ang);c.stroke();c.lineWidth=1;c.globalAlpha=1}else ang=-1.2+Math.sin(t*1.6)*.05;
  if(dir<0)ang=Math.PI-ang;wsWeaponCopy(c,w,bx,by,ang,2.4,now,0,0,WS_W,WS_H)}catch(e){}
 try{const pid=inv.eq.pt||0,pj=k==='pt'&&(t%2.4)<.4?-Math.sin((t%2.4)/.4*Math.PI)*8:0;drawPet(c,pid,px+40+(window.PET105&&!PET105.flies(pid)?0:Math.sin(t*1.3)*4),window.PET105?PET105.at(pid,py-56+Math.sin(t*2.1)*3+pj,py+pj,pid?1.7:1.5):py-56+Math.sin(t*2.1)*3+pj,now,pid?1.7:1.5);
  if(k==='pt'&&(t%2.4)<.9){const q=(t%2.4)/.9;c.globalAlpha=1-q;c.fillStyle='#ff7a9a';const hx2=px+48,hy2=py-70-q*12;c.fillRect(hx2,hy2,2,2);c.fillRect(hx2+3,hy2,2,2);c.fillRect(hx2+1,hy2+2,3,2);c.fillRect(hx2+2,hy2+4,1,1);c.globalAlpha=1}}catch(e){}
 inv.eq.ch=save.ch;inv.eq.wp=save.wp;inv.eq.pt=save.pt;
 /* 계산대 + 부엉이 */const cx0=232;c.fillStyle='#4a2e16';c.fillRect(cx0,110,88,60);c.fillStyle='#6a4424';c.fillRect(cx0-2,106,92,6);c.fillStyle='#8a6434';c.fillRect(cx0-2,106,92,1);c.fillStyle='#2a1a0e';c.fillRect(cx0,112,88,2);
 for(let x=cx0+6;x<cx0+84;x+=16){c.fillStyle='#3a2410';c.fillRect(x,118,12,40);c.fillStyle='#5a3a1c';c.fillRect(x,118,12,1)}
 wsOwl(c,262,106,now,3);/* 금전등록기 */c.fillStyle='#8a6a2a';c.fillRect(290,92,22,14);c.fillStyle='#c89a40';c.fillRect(290,92,22,2);c.fillStyle='#1a1208';c.fillRect(293,95,16,5);c.fillStyle=Math.floor(t*2)%2?'#7dffa8':'#3a8a5a';c.fillRect(295,96,4,3);c.fillStyle='#ffe36b';c.fillRect(300,96,7,3);
 /* 동전 더미 + 종 */for(let n=0;n<4;n++){c.fillStyle=n%2?'#c8901a':'#ffd166';c.fillRect(240,102-n*2,10,2)}c.fillStyle='#c8a050';c.beginPath();c.arc(318-6,104,4,Math.PI,0);c.fill();c.fillRect(308,104,8,1);
 /* 효과 */WS.fx=WS.fx.filter(f=>now-f.t<1600);for(const f of WS.fx){const q=(now-f.t)/1600;if(q<.12&&f.kind==='buy'){c.globalAlpha=(1-q/.12)*.5;c.fillStyle='#ffffff';c.fillRect(0,0,WS_W,WS_H);c.globalAlpha=1}
  for(let n=0;n<(f.kind==='buy'?(f.big?48:30):14);n++){const a=n*2.39996+f.t,r=8+q*70*(0.5+(n%5)/6),x=px+Math.cos(a)*r,y=py-34+Math.sin(a)*r*.7-q*18+q*q*40;c.globalAlpha=1-q;c.fillStyle=n%3===0?'#ffffff':n%3===1?(f.c||col):'#ffe36b';c.fillRect(Math.round(x),Math.round(y),n%4?2:3,n%4?2:3)}
  if(f.kind==='buy'){for(let n=0;n<8;n++){const qq=Math.min(1,q*1.8+n*.05),x=300+(px-300)*qq,y=96+(py-44-96)*qq-Math.sin(qq*Math.PI)*34;c.globalAlpha=qq>=1?0:1;c.fillStyle='#ffd166';c.fillRect(Math.round(x)-2,Math.round(y)-2,4,4);c.fillStyle='#a8781a';c.fillRect(Math.round(x),Math.round(y)-1,1,2)}}}c.globalAlpha=1;
 if(now-WS.newT<1800){const q=(now-WS.newT)/1800,sc=q<.15?2-q/.15:1;c.globalAlpha=q>.8?(1-q)/.2:1;c.save();c.translate(px,py-86);c.scale(sc,sc);wsText(c,'NEW!',0,0,'#ffe36b',16);c.restore();c.globalAlpha=1}
 /* 비네트 */const vg=c.createRadialGradient(WS_W/2,WS_H*.55,WS_H*.35,WS_W/2,WS_H*.5,WS_W*.7);vg.addColorStop(0,'rgba(0,0,0,0)');vg.addColorStop(1,'rgba(0,0,0,.55)');c.fillStyle=vg;c.fillRect(0,0,WS_W,WS_H);
 /* 말풍선 타자 효과 */const bb=$('wsBubble');if(bb){const n=Math.min(WS.sayFull.length,Math.floor((now-WS.sayT)/28)),txt=WS.sayFull.slice(0,n),sp=bb.firstChild;if(sp.textContent!==txt){sp.textContent=txt;if(n%3===0&&n<WS.sayFull.length)try{sfx(900+(n%5)*60,.02,'square',.012,900)}catch(e){}}}}
/* ---- 진열장 미리보기 (등급 배경) ---- */
function wsShelf(now){const t=now/1000,inv=shopInv();document.querySelectorAll('#shopGrid canvas').forEach(cv=>{const c=cv.getContext('2d'),k=cv.dataset.k,i=+cv.dataset.i,it=WS_LIST(k)[i],T=wsTier(it),sel=i===wsSelOf(k);c.imageSmoothingEnabled=false;c.globalAlpha=1;
  const g=c.createRadialGradient(48,56,4,48,52,62);g.addColorStop(0,shade(T.c,.32));g.addColorStop(1,'#0a0806');c.fillStyle=g;c.fillRect(0,0,96,96);
  if(T.k>=3){c.save();c.translate(48,50);c.rotate(t*.35*(T.k>=4?1:.6));c.globalAlpha=T.k>=4?.16:.1;c.fillStyle=T.c;for(let n=0;n<8;n++){c.rotate(TAU/8);c.beginPath();c.moveTo(0,0);c.lineTo(-6,-60);c.lineTo(6,-60);c.closePath();c.fill()}c.restore();c.globalAlpha=1}
  c.fillStyle='#1a1208';c.beginPath();c.ellipse(48,84,30,6,0,0,TAU);c.fill();c.fillStyle=shade(T.c,.4);c.beginPath();c.ellipse(48,83,26,4.5,0,0,TAU);c.fill();
  const bob=sel?Math.round(Math.sin(t*4)*1.5):0,save=inv.eq[k];
  if(k==='ch'){inv.eq.ch=i;try{drawKnight(c,26,38+bob,4,false,null,now/430)}catch(e){}inv.eq.ch=save}
  else if(k==='wp'){try{const w=WEAPONS[i],sp=WSPR[w.type]||WSPR.sword,n=sp.r.length,sc=Math.min(4,70/(n*.72)),ang=-.82+Math.sin(now/700+i)*.05,L=(n-1)*sc*.72,hx=48-Math.cos(ang)*(L/2-sp.g*sc*.72),hy=48+bob-Math.sin(ang)*(L/2-sp.g*sc*.72);wsWeaponCopy(c,w,hx,hy,ang,sc,now,0,0,96,96)}catch(e){}}
  else{try{drawPet(c,i,48,48+bob,now,i?3.2:3)}catch(e){}}
  if(T.k>=2){for(let n=0;n<T.k+1;n++){const q=((t*.6)+n/(T.k+1))%1;c.globalAlpha=Math.sin(q*Math.PI);c.fillStyle='#ffffff';const x=14+((n*53+Math.floor(t*.6+n/(T.k+1))*29)%68),y=16+((n*37)%50);c.fillRect(x,y,1,1);if(q>.3&&q<.7){c.fillRect(x-1,y,3,1);c.fillRect(x,y-1,1,3)}}c.globalAlpha=1}})}
/* ---- 훅 ---- */
{const _rs=renderShop;renderShop=function(){_rs.apply(this,arguments);try{wsBuild();const k=shopTab,L=WS_LIST(k),gr=$('shopGrid');const anim=WS.lastTab!==k;gr.innerHTML=L.map((_,i)=>wsItemHTML(k,i)).join('');gr.classList.toggle('pop',anim);
 const h=$('shopHint');if(h)h.textContent=k==='ch'?'🧥 옷 진열대 · 눌러서 입어보고, 두 번 누르거나 Enter로 구매·장착':k==='wp'?'🗡 무기 진열대 · 눌러서 휘둘러보고, 두 번 누르거나 Enter로 구매·장착':'🐾 펫 진열대 · 눌러서 데려와 보고, 두 번 누르거나 Enter로 구매·장착';
 if(anim){WS.lastTab=k;wsSay({ch:'새 옷 입어볼래? 전부 내가 직접 기웠어.',wp:'날이 잘 선 녀석들만 모아뒀지.',pt:'다들 순한 아이들이야. 하나 데려가!'}[k])}wsRefresh()}catch(e){console.error(e)}}}
{const _os=openShop;openShop=function(tab){WS.sel={ch:null,wp:null,pt:null};WS.lastTab=null;WS.coinShow=null;const r=_os.apply(this,arguments);wsSay('어서 와! 태엽 공방에 온 걸 환영해.');return r}}
{const _dp=drawShopPreviews;drawShopPreviews=function(now){if(!shopOpen)return;if(!$('wsMain'))return _dp.apply(this,arguments);try{wsShelf(now);wsStage(now);wsCoins()}catch(e){}}}
(function(){try{const st=document.createElement('style');st.textContent=
'#shopModal.wsFull{background:radial-gradient(ellipse at 30% 20%,#2a1a0e,#0c0806 70%)!important}#shopModal.wsFull .rushBar{background:linear-gradient(180deg,#3a2616,#24160c)!important;box-shadow:0 4px 0 #0c0806,0 6px 0 #c89a4055!important}'+
'#wsTitle{color:#ffd98a;letter-spacing:.12em;margin-right:8px}#shopModal.wsFull .coinTag{display:inline-flex;align-items:center;gap:6px;padding:4px 12px;border-radius:8px;background:linear-gradient(180deg,#5a4020,#2a1a0c);box-shadow:inset 0 0 0 1px #c89a40,0 2px 0 #000;color:#ffe9a8;font-variant-numeric:tabular-nums;font-size:15px}'+
'#shopModal .coinTag.poorShake{animation:wsShake .35s;color:#ff8a8a}'+
'#wsMain{flex:1;min-height:0;display:grid;grid-template-columns:minmax(300px,.82fr) 1.3fr;gap:16px;padding:14px 16px 16px}'+
'#wsLeft{display:flex;flex-direction:column;gap:10px;min-height:0;overflow:auto;scrollbar-width:thin}#wsStageBox{flex:none;position:relative;border-radius:12px;overflow:hidden;background:#140c08;box-shadow:0 0 0 3px #0c0806,0 0 0 5px #6a4a22,0 10px 30px #000a}#wsCv{display:block;width:100%;height:auto;image-rendering:pixelated}'+
'#wsBubble{position:absolute;right:3%;top:6%;max-width:46%;background:#fff4dc;color:#2a1a0e;border-radius:10px;padding:7px 10px;font-size:12.5px;font-weight:700;line-height:1.45;box-shadow:0 3px 0 #0008,0 0 0 2px #2a1a0e;min-height:1.4em}#wsBubble:after{content:"";position:absolute;right:28%;bottom:-8px;border:8px solid transparent;border-top-color:#fff4dc;border-bottom:0}'+
'#wsTry{position:absolute;left:8px;bottom:8px;font-size:11px;font-weight:900;padding:3px 8px;border-radius:6px;background:#05080acc;color:#ffe9a8;box-shadow:0 0 0 1px #c89a40}'+
'#wsInfo{flex:none;background:linear-gradient(180deg,#24180e,#160e08);border-radius:12px;padding:12px 16px 14px;box-shadow:inset 0 0 0 1px #4a3218,inset 3px 0 0 var(--tc,#c89a40);color:#f4e6c8}'+
'.wsHead{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.wsHead b{font-size:22px;color:#ffe9a8}.wsHead .tier{font-size:11px;font-weight:900;padding:2px 8px;border-radius:10px;color:#0c0806;background:var(--tc)}.wsHead .chip{font-size:11px;font-weight:900;padding:2px 8px;border-radius:10px;box-shadow:inset 0 0 0 1px currentColor}.chip.eq{color:#ffd166}.chip.own{color:#a6f5c6}'+
'.wsSub{margin:4px 0 8px;font-size:12.5px;opacity:.8;line-height:1.5}'+
'.wsRow{display:grid;grid-template-columns:74px 1fr 96px;gap:8px;align-items:center;font-size:12px;margin:3px 0}.wsBar{position:relative;height:9px;border-radius:5px;background:#0c0806;box-shadow:inset 0 0 0 1px #3a2616;overflow:hidden}.wsBar i{position:absolute;left:0;top:0;bottom:0;border-radius:5px;background:#c89a40;transition:width .3s cubic-bezier(.2,1.2,.4,1)}.wsBar i.base{background:#ffffff1f}.wsBar i.up{background:linear-gradient(90deg,#c89a40,#7dffa8)}.wsBar i.dn{background:linear-gradient(90deg,#c89a40,#ff7a7a);opacity:.85}.wsBar u{position:absolute;top:0;bottom:0;width:2px;background:#fff;opacity:.5}'+
'.wsRow b{text-align:right;font-variant-numeric:tabular-nums}.wsRow small{font-size:10px}.wsRow small.up{color:#7dffa8}.wsRow small.dn{color:#ff8a8a}.wsSp{margin-top:6px;font-size:12px;color:#ffd98a}.wsPet{font-size:14px;color:#ffe9a8;margin:4px 0}.wsPet.old{font-size:12px;opacity:.55}'+
'#wsBtn{width:100%;margin-top:10px;padding:11px;font-size:16px;display:flex;flex-direction:column;align-items:center;gap:2px}#wsBtn small{font-size:10.5px;opacity:.75;font-weight:700}#wsBtn.buy{background:linear-gradient(180deg,#ffd166,#c8901a)!important;color:#2a1a0e!important}#wsBtn.own{background:linear-gradient(180deg,#a6f5c6,#4ab88a)!important;color:#0c1a12!important}#wsBtn.poor{opacity:.75;filter:grayscale(.5)}#wsBtn.eq{opacity:.6}#wsBtn.shake{animation:wsShake .35s}@keyframes wsShake{25%{transform:translateX(-7px)}50%{transform:translateX(6px)}75%{transform:translateX(-3px)}}'+
'#wsRight{display:flex;flex-direction:column;min-height:0;border-radius:12px;background:linear-gradient(180deg,#3a2616,#24160c);box-shadow:inset 0 0 0 3px #1a0f07,0 10px 30px #000a;overflow:hidden}'+
'#shopModal.wsFull .shopTabs{border:0;padding:0 16px 4px;gap:14px;justify-content:center;background:linear-gradient(180deg,#1a0f07,#2a1a0e)}'+
'#shopModal.wsFull .shopTab{position:relative;margin-top:18px;padding:9px 18px!important;background:linear-gradient(180deg,#8a5a2a,#5a3a1a)!important;color:#fff0d0!important;border-radius:4px!important;transform:rotate(-2deg);transform-origin:50% -18px;animation:wsSign 3s ease-in-out infinite;box-shadow:0 0 0 2px #1a0f07,0 4px 0 2px #1a0f07!important}'+
'#shopModal.wsFull .shopTab:nth-child(2){animation-delay:-1s}#shopModal.wsFull .shopTab:nth-child(3){animation-delay:-2s}#shopModal.wsFull .shopTab:before,#shopModal.wsFull .shopTab:after{content:"";position:absolute;top:-18px;width:2px;height:18px;background:#1a0f07}#shopModal.wsFull .shopTab:before{left:22%}#shopModal.wsFull .shopTab:after{right:22%}'+
'#shopModal.wsFull .shopTab.on{background:linear-gradient(180deg,#ffd98a,#c8901a)!important;color:#2a1a0e!important}@keyframes wsSign{50%{transform:rotate(2deg)}}'+
'#shopModal.wsFull .rushBody{padding:8px 16px 16px}#shopHint{color:#e8d0a0;opacity:.75;font-size:12px;margin:4px 0 0}'+
'#shopModal.wsFull #shopGrid{grid-template-columns:repeat(auto-fill,minmax(112px,1fr));grid-auto-rows:172px;gap:0 12px;margin-top:4px;background:repeating-linear-gradient(180deg,transparent 0 146px,#7a5028 146px 151px,#5a3a1c 151px 158px,#2a1a0c 158px 161px,transparent 161px 172px)}'+
'.wsItem{position:relative;display:flex;flex-direction:column;align-items:center;justify-content:flex-end;padding-bottom:26px;cursor:pointer;color:#f4e6c8;transition:transform .15s cubic-bezier(.2,1.4,.4,1)}.wsItem:hover{transform:translateY(-3px)}#shopGrid.pop .wsItem{animation:wsPop .4s cubic-bezier(.2,1.5,.4,1) both;animation-delay:var(--ad)}@keyframes wsPop{from{opacity:0;transform:translateY(-14px) scale(.85)}}'+
'.wsItem .dome{width:88px;height:88px;border-radius:44px 44px 8px 8px;overflow:hidden;box-shadow:0 0 0 2px #1a0f07,0 0 0 3px color-mix(in srgb,var(--tc) 40%,#3a2616);position:relative;background:#0a0806}.wsItem .dome:after{content:"";position:absolute;inset:0;border-radius:inherit;background:linear-gradient(115deg,rgba(255,255,255,.26),rgba(255,255,255,0) 32%,rgba(255,255,255,0) 70%,rgba(255,255,255,.08));pointer-events:none}.wsItem canvas{width:100%;height:100%;image-rendering:pixelated;display:block}'+
'.wsItem.t4 .dome{box-shadow:0 0 0 2px #1a0f07,0 0 0 3px var(--tc),0 0 14px color-mix(in srgb,var(--tc) 60%,transparent)}.wsItem.t3 .dome{box-shadow:0 0 0 2px #1a0f07,0 0 0 3px var(--tc)}'+
'.wsItem b{position:absolute;bottom:0;left:50%;transform:translateX(-50%);font-size:10.5px;white-space:nowrap;max-width:112%;overflow:hidden;text-overflow:ellipsis;padding:2px 7px;border-radius:3px;background:linear-gradient(180deg,#c8a050,#8a6424);color:#2a1a0e;box-shadow:0 1px 0 #000,inset 0 1px 0 #ffe9a8}.wsItem b i{font-style:normal;color:#7a2a1a;margin-right:3px;font-size:8px;letter-spacing:-1px}'+
'.wsItem .tg{position:absolute;top:auto;bottom:40px;right:calc(50% - 50px);font-style:normal;font-size:10px;font-weight:900;padding:2px 6px;border-radius:3px;background:#f4e6c8;color:#2a1a0e;transform:rotate(var(--sw));transform-origin:80% -6px;animation:wsTag 2.6s ease-in-out infinite;animation-delay:var(--dl);box-shadow:0 2px 0 #0006;z-index:2}.wsItem .tg:before{content:"";position:absolute;right:30%;top:-6px;width:1px;height:6px;background:#1a0f07}'+
'.wsItem .tg.poor{background:#c8b8a0;color:#7a3a2a}.wsItem .tg.own{background:#a6f5c6;color:#0c1a12}.wsItem .tg.eq{background:#ffd166;color:#2a1a0e}@keyframes wsTag{50%{transform:rotate(calc(var(--sw) * -1))}}'+
'.wsItem.sel .dome{box-shadow:0 0 0 2px #1a0f07,0 0 0 4px #ffd166,0 0 20px #ffd166aa}.wsItem.sel{transform:translateY(-5px)}.wsItem.eq .dome{box-shadow:0 0 0 2px #1a0f07,0 0 0 4px #a6f5c6}.wsItem.sel.eq .dome{box-shadow:0 0 0 2px #1a0f07,0 0 0 4px #ffd166,0 0 0 6px #a6f5c6,0 0 18px #ffd166}'+
'.wsStamp{position:absolute;left:50%;top:32%;font-weight:900;font-size:22px;color:#ff4d4d;border:3px solid #ff4d4d;border-radius:6px;padding:0 8px;background:#fff4dcdd;transform:translate(-50%,-50%) rotate(-14deg);animation:wsStampIn .35s cubic-bezier(.2,1.6,.4,1) both;pointer-events:none;z-index:3}@keyframes wsStampIn{from{transform:translate(-50%,-50%) rotate(-14deg) scale(2.6);opacity:0}}'+
'@media (max-width:820px){#wsMain{display:flex;flex-direction:column;overflow:auto;padding:10px;gap:10px}#wsMain>*{flex:none}#wsLeft{overflow:visible}#wsRight{overflow:visible}#wsBubble{font-size:11px;max-width:52%}#shopModal.wsFull .rushBar span{font-size:12px}}';
(document.head||document.body).appendChild(st)}catch(e){}})();

